

import LandingPage from '@/pages/home/LandingPage.jsx';
import ServicesList from '@/pages/services/Services.jsx';
import NewService from '@/pages/user-defined-service/NewService.jsx';
import Estimate from '@/pages/estimate/Estimate.jsx';
import PDFView from '@/pages/export/PDFView.jsx';
import NotFound from '@/pages/notFound/NotFound.jsx';
import { camelCase } from '@/utils/string.js';


/**
 * @typedef {Object} Route
 * @property {string} path - The URL path for the route.
 * @property {function(Object=): JSX.Element} element - A function that returns the React component to render for the route, optionally accepting props.
 * @property {string} label - The display label for the route, used in navigation.
 * @property {boolean} showNav - Determines if the route should be shown in the navigation bar.
 */

/**
 * An array of route configuration objects for the application.
 * @type {Route[]}
 */
const routes = [
  {
    path: '/',
    element:  (props) => <LandingPage {...props}/>,
    label: 'Home',
    showNav: false,
  },
  {
    path: '/services',
    element: (props) => <ServicesList {...props}/>,
    label: 'Services',
    showNav: true,
  },
  {
    path: '/services/new',
    element: (props) => <NewService {...props}/>,
    label: 'New Service',
    showNav: true,
  },
  {
    path: '/estimate',
    element: () => <Estimate />,
    label: 'Estimate',
    showNav: true,
  },
  {
    path: '/estimate/pdf',
    element: () => <PDFView />,
    label: 'Estimate Preview',
    showNav: true,
  },
  {
    path: '*',
    element: () => <NotFound/>,
    label: 'Not Found',
    showNav: false,
  },

];


/**
 * An object mapping normalized route labels to their corresponding paths.
 * The keys are generated by converting each route's label to lowercase and replacing spaces with hyphens.
 * Only routes with a label and a path not equal to '*' are included.
 *
 * @type {Object.<string, string>}
 */
const pages = Object.fromEntries(
  routes
    .filter(route => route.label && route.path !== '*')
    .map(route => [
      camelCase(route.label),
      route.path
    ])
);

export const usePages = () => {
  return pages;
}

export const useOnPage = (location) => {
    return (page) => {
        const path = pages[page];
        if (!path) return false;
        return location.pathname === path;
    };
};

export const useShowNav = (location) => {
    const currentRoute = routes.find(r => r.path === location.pathname);
    return !!currentRoute?.showNav;
}



export { routes as default };
