

import LandingPage from '@/pages/home/LandingPage.jsx';
import ServicesList from '@/pages/services/Services.jsx';
import NewService from '@/pages/custom-service/NewService.jsx';
import EditService from '@/pages/custom-service/EditService.jsx';
import Estimate from '@/pages/estimate/Estimate.jsx';
import PDFView from '@/pages/export/PDFView.jsx';
import NotFound from '@/pages/notFound/NotFound.jsx';
import RootLayout from '@/pages/RootLayout.jsx';
import { createHashRouter } from 'react-router-dom';
import { camelCase } from '@/utils/string.js';

/**
 * @typedef {Object} Route
 * @property {string} [path] - The URL path for the route.
 * @property {function(Object=): JSX.Element|JSX.Element} element - The React component to render for the route, optionally accepting props.
 * @property {Object} [handle] - Metadata for the route.
 * @property {Route[]} [children] - Nested child routes.
 */

/**
 * An array of route configuration objects for the application.
 * @type {Route[]}
 */

const routes = [
  {
    element: <RootLayout />,
    children: [
      {
        path: '/',
        element: <LandingPage/>,
        handle: { showNav: false, title: 'Home' },
      },
      {
        path: '/services',
        element: <ServicesList/>,
        handle: { showNav: true, title: 'Services' },
      },
      {
        path: '/services/new',
        element: <NewService/>,
        handle: { showNav: true, title: 'New Service' },
      },
      {
        path: '/services/:id/edit',
        element: <EditService/>,
        handle: { showNav: true, title: 'Edit Service' },
      },
      {
        path: '/estimate',
        element: <Estimate/>,
        handle: { showNav: true, title: 'Estimate' },
      },
      {
        path: '/estimate/pdf',
        element: <PDFView/>,
        handle: { showNav: true, title: 'Estimate Preview' },
      },
      {
        path: '*',
        element: <NotFound/>,
        handle: { showNav: false, title: 'Not Found' },
      },
    ],
  },
];

const useRoutes = () => routes;

const router = createHashRouter(routes);

export { router as default, useRoutes };


/**
 * An object mapping normalized route labels to their corresponding paths.
 * The keys are generated by converting each route's label to lowercase and replacing spaces with hyphens.
 * Only routes with a label and a path not equal to '*' are included.
 *
 * @type {Object.<string, string>}
 */
function getAllRoutes(routeList) {
  let result = [];
  for (const route of routeList) {
    if (route.handle?.title && route.path && route.path !== '*') {
      result.push([camelCase(route.handle.title), route.path]);
    }
    if (route.children) {
      result = result.concat(getAllRoutes(route.children));
    }
  }
  return result;
}

const pages = Object.fromEntries(getAllRoutes(routes));

export const usePages = () => {
  return pages;
}